// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using contact_list_api;

#nullable disable

namespace contact_list_api.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20230530111510_add_office_number_field")]
    partial class add_office_number_field
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("contact_list_api.Models.Contact", b =>
                {
                    b.Property<long>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OfficePhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1L,
                            DateOfBirth = new DateTime(1991, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elvis@eblocks.co.za",
                            FirstName = "Elvis",
                            LastName = "Thelemuka",
                            OfficePhoneNumber = "011-607-0756",
                            PhoneNumber = "073-607-0756"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
